name: node-semver-hs
version: 0.1.0.0
license: BSD-3-Clause
author: "arark"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description: Please see the README on GitHub at <https://github.com/githubuser/npm-instsall-hs#readme>

dependencies:
  - base >= 4.7 && < 5
  - semver
  # - array

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - ImportQualifiedPost
  - OverloadedStrings

library:
  source-dirs: src
  dependencies:
    - semver
    - text
    - array >= 0.5
  build-tools:
    - happy >= 1.20
    - alex >= 3.3
  exposed-modules:
    - Data.SemVer.Node.Parser
    - Data.SemVer.Node.Lexer
    - Data.SemVer.Node
  other-modules:
    - Data.SemVer.Node.Internal

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - node-semver-hs
      - HUnit
      - semver
      - text
