name: node-semver-hs
version: 0.1.0.0
license: BSD-3-Clause
author: "arark"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description: Please see the README on GitHub at <https://github.com/githubuser/npm-instsall-hs#readme>

ghc-options:
  - -Wall
  - -O2

language: GHC2021

default-extensions:
  - ImportQualifiedPost
  - OverloadedStrings

dependencies:
  - base
  - semver
  - text

library:
  source-dirs: src
  dependencies:
    - array >= 0.5
    - transformers
  build-tools:
    - happy >= 1.20
    - alex >= 3.3
  exposed-modules:
    - Data.SemVer.Node
    - Data.SemVer.Node.Parser
    - Data.SemVer.Node.Lexer
    - Data.SemVer.Node.Token
    - Data.SemVer.Node.AST

tests:
  test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - node-semver-hs
      - HUnit
      - tasty
      - tasty-hunit

benchmarks:
  benchmark:
    main: Main.hs
    source-dirs: bench
    dependencies:
      - node-semver-hs
      - tasty-bench
